---
- hosts: minecraft_server
  become: yes
  tasks:
    - name: Update and upgrade packages using yum
      yum:
        name: '*'
        state: latest

    - name: Install OpenJDK 17
      yum:
        name: java-17-amazon-corretto-headless
        state: present

    - name: Create a directory for Minecraft server
      file:
        path: /opt/minecraft
        state: directory
        mode: '0755'

    - name: Download Minecraft server
      get_url:
        url: https://piston-data.mojang.com/v1/objects/84194a2f286ef7c14ed7ce0090dba59902951553/server.jar
        dest: /opt/minecraft/server.jar

    - name: Accept Minecraft EULA
      copy:
        dest: /opt/minecraft/eula.txt
        content: 'eula=true'

    - name: Create systemd service for Minecraft server 
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/opt/minecraft
          ExecStart=/usr/bin/java -Xmx1024M -Xms1024M -jar /opt/minecraft/server.jar nogui
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to register Minecraft service
      systemd:
        daemon_reload: yes

    - name: Start and enable Minecraft service
      systemd:
        name: minecraft
        state: started
        enabled: yes
